# Generated by Django 5.2.6 on 2025-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('book', 'Livre'), ('cd', 'CD'), ('dvd', 'DVD'), ('board-game', 'Jeu de plateau')], max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('by', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
