# Generated by Django 5.2.6 on 2025-09-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='title',
        ),
    ]
