# Generated by Django 5.2.6 on 2025-09-16 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_rename_by_media_author_rename_name_media_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.media')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.borrower')),
            ],
        ),
    ]
