# Generated by Django 5.2.6 on 2025-09-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0003_borrower_alter_media_author_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='borrower_id',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='media_id',
            new_name='media',
        ),
    ]
