# Generated by Django 5.2.6 on 2025-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0004_rename_borrower_id_borrow_borrower_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrower',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='date',
            new_name='borrowing_date',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='borrower',
            new_name='member',
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
