# Generated by Django 5.2.6 on 2025-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0005_rename_borrower_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
